version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: discord-clone
    volumes:
      - D:\learn\database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgadmin-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: sitthisakbannob@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - pgadmin-network

networks:
  pgadmin-network:
    driver: bridge
